import type { Metadata } from "next";
import localFont from "next/font/local";
import { Tiny5 } from "next/font/google";

import "./globals.css";

const tiny5 = Tiny5({ subsets: ["latin"], weight: "400" }); // Adjust 'weight' as needed

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tiny5.className}`}>{children}</body>
    </html>
  );
}
